var a = 'vasanth';
console.log(typeof(a));
var b = 25;
console.log(typeof(b));
var c = null;
console.log(typeof(c));
var d ;
console.log(typeof(d));
var e = ['C', 'C++', 'JAVA'];
console.log(typeof(e));
var f = {'name':'vasanth','age':25};
console.log(typeof(f));
var g = true;
console.log(typeof g);
var h1=Symbol();
var h2=Symbol();
console.log(typeof h1);
console.log(h1==h2);
var i=new Date();
console.log(i);
console.log(typeof i);
